float:
  any:
  - base_args: {}
    constructor: Sgia
    disabled: false
    docker_tag: ann-benchmarks-sgia
    module: ann_benchmarks.algorithms.sgia
    name: sgia
    run_groups:
      sgia:
        args: []
        query_args: [[100, 200, 400, 1000, 2000, 4000, 10000, 20000, 40000, 100000,
            200000, 400000]]