float:
  any:
  - base_args: ['@metric']
    constructor: Sgia
    disabled: false
    docker_tag: ann-benchmarks-sgia
    module: ann_benchmarks.algorithms.sgia
    name: sgia
    run_groups:
      redisearch:
        arg_groups: [[200]]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]