float:
  any:
  - base_args: ['@metric', Float, 0.1]
    constructor: ONNG
    disabled: true
    docker_tag: ann-benchmarks-onng_ngt
    module: ann_benchmarks.algorithms.onng_ngt
    name: NGT-onng
    run_groups:
      e0.02:
        args: [{edge: 100, epsilon: 0.02, indegree: 120, outdegree: 10}]
        query_args: [[[0.6, -2], [0.9, -2], [1.0, -2], [1.02, -2], [1.03, -2], [1.04,
              -2], [1.05, -2], [1.07, -2], [1.1, -2], [1.2, -2]]]
