float:
  any:
  - base_args: ['@metric']
    constructor: FaissLSH
    disabled: true
    docker_tag: ann-benchmarks-faiss
    module: ann_benchmarks.algorithms.faiss
    name: faiss-lsh
    run_groups:
      base:
        args: [[128]]
