float:
  angular:
  - base_args: {}
    constructor: Scann
    disabled: false
    docker_tag: ann-benchmarks-scann
    module: ann_benchmarks.algorithms.scann
    name: scann
    run_groups:
      scann1:
        args: [[2000], [0.2], [2], [dot_product]]
        query_args: [[[1, 30], [2, 30], [4, 30], [8, 30], [30, 120], [35, 100], [
              40, 80], [45, 80], [50, 80], [55, 95], [60, 110], [65, 110], [75, 110],
            [90, 110], [110, 120], [130, 150], [150, 200], [170, 200], [200, 300],
            [220, 500], [250, 500], [310, 300], [400, 300], [500, 500], [800, 1000]]]
