float:
  any:
  - base_args: ['@metric']
    constructor: BruteForce
    disabled: true
    docker_tag: ann-benchmarks-bruteforce
    module: ann_benchmarks.algorithms.bruteforce
    name: bruteforce
    run_groups:
      empty:
        args: []
