name: ANN benchmarks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel the workflow for the previous commit when the new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Pull the repository
      - run: sudo apt-get update && sudo apt-get install -y libhdf5-dev python3-numpy python3-scipy python3-matplotlib python3-sklearn
      - run: pip3 install --quiet -r requirements.txt
      - run: pytest

  run-benchmarks:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3 # Pull the repository

    - name: Install OS Dependencies
      run: sudo apt-get update && sudo apt-get install -y libhdf5-dev python3-numpy python3-scipy python3-matplotlib python3-sklearn

    - name: Install Project Dependencies
      run: pip3 install --quiet -r requirements.txt

    # build the docker images for the algorithms ckdtree and kdtree
    - name: Build Library Docker Image
      run: |
        python3 install.py --algorithm ckdtree
        python3 install.py --algorithm kdtree


    - name: Run the benchmark
      run: |
        # get all existing docker images
        docker images
        python3 run.py
        sudo chmod -R 777 results/
        python3 plot.py --output plot-batch.png --batch
        python3 data_export.py --out test.csv
        python3 create_website.py --outputdir . --scatter --latex

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: .
