name: ANN benchmarks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel the workflow for the previous commit when the new commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  run-benchmarks:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3 # Pull the repository

    - name: Install OS Dependencies
      run: sudo apt-get update && sudo apt-get install -y libhdf5-dev python3-numpy python3-scipy python3-matplotlib python3-sklearn

    - name: Install Project Dependencies
      run: pip3 install --quiet -r requirements.txt

    # build the docker images for the algorithms ckdtree and kdtree
    - name: Build Library Docker Image
      run: |
        # python3 install.py
        python3 install.py --algorithm annoy
        python3 install.py --algorithm hnswlib
        python3 install.py --algorithm kdtree
        python3 install.py --algorithm sgia

        # python3 install.py --algorithm bruteforce
        # python3 install.py --algorithm faiss
        # python3 install.py --algorithm mrpt
        # python3 install.py --algorithm onng_ngt
        # python3 install.py --algorithm scann

    - name: Run the benchmark
      run: |
        # get all existing docker images
        docker images
        sudo usermod -aG docker $USER
        export DOCKER_HOST=unix:///var/run/docker.sock
        docker version
        sudo chmod 666 /var/run/docker.sock
        python run.py --max-n-algorithms 4 --runs 1 --dataset random-xs-20-angular --run-disabled --timeout 300
        # python run.py --algorithm ckdtree --output results/ckdtree.json
        # python run.py --algorithm kdtree --output results/kdtree.json
        sudo chmod -R 777 results/
        python3 plot.py --dataset random-xs-20-angular --output plot-batch.png 
        python3 data_export.py --out test.csv
        python3 create_website.py --outputdir . --scatter --latex

    # - name: Upload results
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: results
    #     path: .

    # - name: publish website
    #   uses: JamesIves/github-pages-deploy-action@4.1.1
    #   with:
    #     branch: gh-pages
    #     folder: .
    #     clean: true
    #     token: ${{ secrets.GITHUB_TOKEN }}
